version: "3.3"

services:
  nats-1:
    image: nats:2.1.9-alpine
    volumes:
      - ./../nats/cluster.conf:/etc/nats/nats-server.conf
    env_file:
      - .env

  nats-2:
    image: nats:2.1.9-alpine
    volumes:
      - ./../nats/cluster.conf:/etc/nats/nats-server.conf
    env_file:
      - .env

  nats-3:
    image: nats:2.1.9-alpine
    volumes:
      - ./../nats/cluster.conf:/etc/nats/nats-server.conf
    env_file:
      - .env

  pub_order_created:
    build:
      context: ../apps/publisher
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NATS_SUBJECT=event.order.created
      - NATS_URL=nats-1:4222
    depends_on:
      - nats-1

  sub_order:
    build:
      context: ../apps/subscriber
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NATS_SUBJECT=event.order.created
      - NATS_URL=nats-3:4222
    depends_on:
      - nats-3