version: "3.3"

services:
  nats-1:
    image: nats:2.1.9-alpine
    volumes:
      - ../../nats/cluster-1.conf:/etc/nats/nats-server.conf
    env_file:
      - .env

  nats-2:
    image: nats:2.1.9-alpine
    volumes:
      - ../../nats/cluster-2.conf:/etc/nats/nats-server.conf
    env_file:
      - .env

  nats-3:
    image: nats:2.1.9-alpine
    volumes:
      - ../../nats/cluster-3.conf:/etc/nats/nats-server.conf
    env_file:
      - .env

  pub_order:
    build:
      context: ../../src/publisher
      dockerfile: ../../src/Dockerfile
    env_file:
      - .env
    environment:
      - NATS_SUBJECT=event.order.created
      - NATS_URL=nats-1:4222
    depends_on:
      - nats-1
    command: ["sleep", "1200s"]

  sub_order:
    build:
      context: ../../src/subscriber
      dockerfile: ../../src/Dockerfile
    env_file:
      - .env
    environment:
      - NATS_SUBJECT=event.order.created
      - NATS_URL=nats-3:4222
    depends_on:
      - nats-3
